# Generated by Django 5.2 on 2025-05-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pkac_code', models.CharField(max_length=11500)),
                ('Ac_name', models.CharField(default=None, max_length=150, null=True)),
                ('Ac_type', models.CharField(default=None, max_length=50, null=True)),
                ('Ac_nature', models.CharField(default=None, max_length=50, null=True)),
                ('Sh_code', models.CharField(default=None, max_length=150, null=True)),
                ('Sh_name', models.CharField(default=None, max_length=150, null=True)),
                ('Company', models.CharField(max_length=150)),
                ('Branch', models.CharField(blank=True, default='All', max_length=150)),
                ('Sub_l', models.CharField(max_length=150)),
                ('HOBR', models.CharField(default=None, max_length=150, null=True)),
                ('Sys_date_time', models.DateTimeField(blank=True)),
                ('Sub_code', models.CharField(blank=True, default='0000', max_length=150)),
                ('Sub_name', models.CharField(blank=True, default='Nil', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('B_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Branch_code', models.CharField(max_length=100)),
                ('Branch_name', models.CharField(default=None, max_length=150, null=True)),
                ('active', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=150)),
                ('relation', models.CharField(max_length=150)),
                ('relation_name', models.CharField(max_length=150)),
                ('photo', models.FileField(blank=True, null=True, upload_to='staff_photos/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='staff_signatures/')),
                ('house_name', models.CharField(max_length=150)),
                ('house_no', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('post_office', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('mobile1', models.CharField(max_length=150)),
                ('mobile2', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Branch_code', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_daybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fk_accode', models.CharField(max_length=150)),
                ('Sub_code', models.CharField(max_length=150)),
                ('Branch_code', models.CharField(default=None, max_length=150, null=True)),
                ('User_id', models.IntegerField()),
                ('Trans_id', models.IntegerField()),
                ('Ac_date', models.DateField(default=None, null=True)),
                ('Mode', models.CharField(default=None, max_length=150, null=True)),
                ('Trans_amount', models.FloatField(default=None, null=True)),
                ('Narration', models.TextField(default=None, null=True)),
                ('Remark', models.CharField(blank=True, max_length=150)),
                ('Type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Password', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Company', models.CharField(blank=True, max_length=150)),
                ('User_level', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('B_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apk.branch')),
            ],
        ),
    ]
