# Generated by Django 5.2 on 2025-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_daybook',
            name='crcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
