# Generated by Django 5.2 on 2025-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_temp_daybook_crcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_daybook',
            name='Bank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
